language: c
dist: xenial
sudo: required

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu cosmic main"
  - sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu cosmic universe"
  - sudo apt-get -qq update
  - sudo apt-get dist-upgrade
  - sudo apt-get install -y cmake && sudo apt-get install -y cpputest && sudo apt-get install -y gcc && sudo apt-get install -y libcpputest-dev && sudo apt-get install -y clang

script:
  - mkdir build && cd build
  - cmake ..
  - make
  - make test
